version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Server=host.docker.internal;Database=PointOnSaleDb;User Id=SZDB2;Password=SZDB212345678;TrustServerCertificate=True;MultipleActiveResultSets=true
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - pos-network

  frontend:
    build:
      context: ./web/point-on-sale-web
      dockerfile: Dockerfile
    environment:
      - VITE_API_URL=/v1
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - pos-network

networks:
  pos-network:
    driver: bridge

